name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        pr-message:  'Hello @${{ github.actor }}, thank you for submitting a PR! We will respond as soon as possible.'
        issue-message: |
          Hello @${{ github.actor }}, thank you for your interest in youdotcom/betterapi.

          If this is a bug/issue with the api (betterapi.net) note that this is still in beta. 

          Please note that repository is made and maintained by a single developer, @SilkePilon.


          Thank you for submitting a issue! @SilkePilon will respond as soon as possible.




          
